todolist/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todolists/', include(('todolists.urls', 'todolists'), namespace="todolists")),
]

todolists/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="Index"),
    url(r'^addtask/$', views.addtask, name="Addtask"),
    url(r'^dotask/$', views.dotask, name="Dotask"),
]

todolists/models.py
from django.db import models


# Create your models here.
class todotask(models.Model):
    taskname = models.CharField(max_length=200)
    dostatus = models.BooleanField(default=False)

    def __str__(self):
        return self.taskname

todolists/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import todotask


# Create your views here.
def index(request):
    dotask = todotask.objects.filter(dostatus=True)
    undotask = todotask.objects.filter(dostatus=False)
    context = {
        'dotask': dotask,
        'undotask': undotask,
    }
    return render(request, 'todolists/index.html', context)


def addtask(request):
    taskname = request.POST['addtask']
    # taskname = "Test 2"
    task = todotask(taskname=taskname, dostatus=False)
    task.save()
    return HttpResponseRedirect(reverse('todolists:Index'))

def dotask(request):
    if request.method == 'GET':
        taskid = request.GET['taskid']
        try:
            task = todotask.objects.get(id = taskid)
        except todotask.DoesNotExist:
            return HttpResponseRedirect(reverse('todolists:Index'))
        task.dostatus = True
        task.save()
        return HttpResponse("Success")
    else:
        return HttpResponse("Fail")

todolists/templates/todolists/footer.html
<div class="row">
    <div class="col-sm-12">
        <hr>
        For Test By Sapjarern
        <hr>
    </div>
</div>

todolists/templates/todolists/header.html
<div class="row">
    <div class="col-sm-12">
        <h2>My To Do List</h2>
        <hr>
    </div>
</div>

todolists/templates/todolists/index.html
{% extends 'todolists/template.html' %}
{% block main_content %}
<h3>สิ่งที่ต้องทำ</h3>
<div class="row text-left">
    <div class="col-sm-4"></div>
    <div class="col-sm-4">
    {% if undotask %}
        {% for task in undotask %}
            <div class="form-check" id="undotaskG">
                <input type="checkbox" name="task" id="undotask{{ forloop.counter }}" value="{{ task.id }}" class="form-check-input">
                <label for="undotask{{ forloop.counter }}" class="form-check-label">{{ task.taskname }}</label>
            </div>
        {% endfor %}
    {% else %}
        <p>Don't have Task</p>
    {% endif %}
    </div>
    <div class="col-sm-4">
        <form action="{% url 'todolists:Addtask' %}" method="post">
            {% csrf_token %}
            <div class="input-group input-group-sm mb-3">
                <input type="text" class="form-control" name="addtask" id="addtask">
                <div class="input-group-append">
                    <button class="btn btn-secondary" type="submit" id="addtaskBT">เพิ่ม</button>
                </div>
            </div>
        </form>

    </div>
</div>

<h3>ทำสำเร็จแล้ว</h3>
<div class="row text-left">
    <div class="col-sm-4"></div>
    <div class="col-sm-4">
    {% if dotask %}
        {% for task in dotask %}
            <div class="form-check" id="dotask">
                <input type="checkbox" name="task" id="dotask{{ forloop.counter }}" value="{{ task.id }}" checked disabled class="form-check-input">
                <label for="dotask{{ forloop.counter }}" class="form-check-label"><s>{{ task.taskname }}</s></label>
            </div>
        {% endfor %}
    {% else %}
        <p>Don't have Task</p>
    {% endif %}
    </div>
    <div class="col-sm-4"></div>
</div>

{% endblock %}

todolists/templates/todolists/template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Todo List</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container text-center" style="background-color: papayawhip">
{% include "todolists/header.html" %}

{% block main_content %}
{% endblock %}

{% include "todolists/footer.html" %}
</div>
<script>
$(document).ready(function(){
  $(":checkbox").click(function(){
      var id = this.value;
      console.log(this.value);
      $.ajax({
          type: 'GET',
          url: "dotask",
          data: {taskid: id},
          success: function (result) {
              console.log(result);
              if (result == "Success"){
                  window.location.reload(true);
              }
              else {
                  alert("เกิดข้อผิดพลาด กรุณาลองให่ม่อีกครั้ง")
                  window.location.reload(true);
              }
          }
      })
  })
});
</script>
</body>
</html>